//
// Install artifacts locally or deploy and release articats to maven repository
//
// https://github.com/smh/grunt-maven-tasks
//
module.exports = {
	options: { 
		groupId: '<%= pkg.config.maven_tasks.groupId %>',
	},
	debug: {
		options: {
			goal: 'deploy',
			repositoryId: '<%= pkg.config.maven_tasks.repositories.snapshot.id %>',
			url: '<%= pkg.config.maven_tasks.repositories.snapshot.url %>'
		},
		src: [ 'dist/**' ]
	},
	release: {
		options: {
			goal: 'release',
			repositoryId: '<%= pkg.config.maven_tasks.repositories.release.id %>',
			url: '<%= pkg.config.maven_tasks.repositories.release.url %>',
			commitPrefix: '<%= pkg.config.maven_tasks.commit_prefix %> autogenerated by maven-task plugin: '
		},
		src: [ 'dist/**' ]
	}
}
