//
// Install artifacts locally or deploy and release articats to maven repository. 
//
// As the release target automatically increments the version number of the project, 
// in order for release to work properly everything will need to have been commited to 
// git prior to running the task.
//
// https://github.com/smh/grunt-maven-tasks
//
module.exports = {
	options: { 
		groupId: '<%= pkg.config.maven.groupId %>',
	},
	debug: {
		options: {
			goal: 'deploy',
			repositoryId: '<%= pkg.config.maven.repositories.snapshot.id %>',
			url: '<%= pkg.config.maven.repositories.snapshot.url %>'
		},
		src: [ 'dist/**' ]
	},
	release: {
		options: {
			goal: 'release',
			repositoryId: '<%= pkg.config.maven.repositories.release.id %>',
			url: '<%= pkg.config.maven.repositories.release.url %>',
			commitPrefix: '<%= pkg.config.maven.commit_prefix %> autogenerated by maven-task plugin: '
		},
		src: [ 'dist/**' ]
	},
	release-deploy-only: {
		options: {
			goal: 'deploy',
			repositoryId: '<%= pkg.config.maven.repositories.release.id %>',
			url: '<%= pkg.config.maven.repositories.release.url %>'
		},
		src: [ 'dist/**' ]
	}
}
